sonar.projectKey=thomasprade_thro-sqs-2026
sonar.organization=thomasprade

sonar.sources=backend/src,frontend/src
sonar.tests=backend/src,frontend/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/main.ts,**/*.module.ts

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,backend/coverage-e2e/lcov.info,frontend/coverage/lcov.info,frontend/coverage-e2e/lcov.info