site_name: SQS Recipe App
site_description: Development instructions to a app that hosts your homemade recipes for friends & family

# Repository
repo_name: thomasprade/thro-sqs-2026
repo_url: https://github.com/thomasprade/thro-sqs-2026

# Copyright
copyright: Made by Team 'Exorbitant SQS'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - navigation.footer
    - navigation.indexes
    - search.highlight
    - search.suggest
    - content.code.copy
    - toc.follow
    - header.autohide
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: orange
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Lato
    code: Roboto Mono
  icon:
    logo: material/silverware-fork-knife

docs_dir: .

plugins:
  - search
  - mkdocstrings:
      default_handler: python
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_retries: 20
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - md_in_html

# Page tree
nav:
  - Home:
      - Home: index.md
      - arc42:
          - arc42/01_introduction_and_goals.md
          - arc42/02_architecture_constraints.md
          - arc42/03_context_and_scope.md
          - arc42/04_solution_strategy.md
          - arc42/05_building_block_view.md
          - arc42/06_runtime_view.md
          - arc42/07_deployment_view.md
          - arc42/08_crosscutting_concepts.md
          - arc42/09_architecture_decisions.md
          - arc42/10_quality.md
          - arc42/11_risks_and_technical_dept.md
          - arc42/12_glossary.md
      - adr:
          - adr/adr001_core_architecture.md
          - adr/adr002_secure_endpoint.md
          - adr/adr003_node_version.md
          - adr/adr004_orm.md
          - adr/adr005_docker_setup.md
          - adr/adr006_chosen_languages_and_frameworks.md
          - adr/adr007_testing_strategy.md
          - adr/adr008_database.md
